Update fzf install instruction

diff --git a/subcommands/zenlog-fzf-wrapper b/subcommands/zenlog-fzf-wrapper
--- a/subcommands/zenlog-fzf-wrapper
+++ b/subcommands/zenlog-fzf-wrapper
@@ -18,6 +18,6 @@ if (( $? == 127 )) ; then
 #        exit 1
 #    fi
 
-    echo $'zenlog: FZF not found. Run this command to install: \e[1;33mgo get -u github.com/junegunn/fzf\e[0m' 1>&2
+    echo $'zenlog: FZF not found. Get it from: \e[1;33mhttp://github.com/junegunn/fzf\e[0m' 1>&2
     exit 1
 fi
